### ISSUE TITLE
At lg viewport, the text on the header is still too close to border

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers#10] opened 2016-09-13 09:30 UTC
I suppose we still need to add some margin (or padding) to add some space from the border. 
PS: this of course occurs on every template
![margin](https://cloud.githubusercontent.com/assets/19909772/18468524/b717be62-79a4-11e6-9806-498659b2ca33.PNG)

**Comment by matthewmorek** [comment] 2016-09-13 10:42
Sadly, I can't reproduce this issue on my end. It works fine on viewports of `1024px` or above. See screenshot here: http://jmp.sh/T2o4ibX.

**Comment by matthewmorek** [comment] 2016-09-13 12:41
Fixed in 4b43757eb09e2cb31b646b6f27a4bdec70879777.

**Closed by matthewmorek** 2016-09-13 12:41 UTC
